"""
parsers.sec_html_parser
─────────────────────────
Fetches and archives a filing's original HTML (the existing PDF-only
ingestion path throws this away — see services/sec_fetch.py, which only ever
calls findata.download_filing_pdf), then parses its footnote graph: which
statement line item points at which Note, so
services.structured_db.statement_footnote_links can answer "why did this
change" questions (see implementation_plan/new_db_architecture_plan/
Phase5_Agent_Orchestration.md's footnote_tool).

Best-effort by design: parse_footnote_graph() returns [] on ANY failure —
this is enrichment layered on top of the XBRL numeric facts
(providers/edgar_xbrl.py), never a hard requirement for ingestion to
succeed. The heading/reference patterns below were calibrated against a
real Broadcom 10-K (not synthetic data) — SEC filings are auto-generated by
several different vendors (Workiva, Donnelley, ...) and vary in exact
whitespace/markup, so the regexes are intentionally permissive.
"""

from __future__ import annotations

import logging
import re
import warnings
from dataclasses import dataclass

import httpx
from bs4 import BeautifulSoup, XMLParsedAsHTMLWarning

from services import data_lake

logger = logging.getLogger(__name__)

# Same SEC etiquette as providers/edgar_xbrl.py.
_USER_AGENT = "FinAnalSupTool dev@finanalst.local"
_HTTP_TIMEOUT = 30.0

# Modern SEC filings are Inline XBRL: XHTML with an <?xml ...?> prolog and
# ix:* namespaces layered over ordinary HTML. BeautifulSoup's HTML parser
# handles the content just fine but warns that it looks like XML — that
# warning is expected here, not a sign anything is wrong.
warnings.filterwarnings("ignore", category=XMLParsedAsHTMLWarning)


async def fetch_and_archive_html(
    document_url: str, ticker: str, period_label: str
) -> str | None:
    """
    GET the raw filing HTML directly from document_url — the SAME document
    services.sec_fetch renders to PDF, but read here as text before any
    rendering — and archive it via data_lake.save_raw before any parsing.

    Returns the HTML text, or None on any fetch failure. Never raises: a
    failed fetch here must not take down the PDF-based ingestion path that
    may already have succeeded for this same filing.
    """
    try:
        async with httpx.AsyncClient(
            headers={"User-Agent": _USER_AGENT}, timeout=_HTTP_TIMEOUT, follow_redirects=True
        ) as client:
            resp = await client.get(document_url)
            resp.raise_for_status()
            html = resp.text
    except Exception as e:  # noqa: BLE001 — best-effort enrichment, never fails the caller
        logger.warning(f"[sec_html_parser] fetch failed for {document_url}: {e}")
        return None

    data_lake.save_raw(ticker, "sec_filing_html", period_label, "html", html)
    return html


@dataclass
class FootnoteLink:
    statement_item: str
    note_id: str
    note_title: str | None
    note_text: str


# A note's own heading inside "Notes to Consolidated/Condensed Financial
# Statements": a standalone "N." followed by a Title-Case heading, e.g.
# "9. \nBorrowings" or "12. Segment Information" (both real forms seen in a
# live Broadcom 10-K — exact line-break placement varies by filing vendor).
_NOTE_HEADING_RE = re.compile(
    r"\n[ \t]*(\d{1,2})\.[ \t]*\n?[ \t]*([A-Z][A-Za-z ,&'\-]{3,60})[ \t]*\n"
)

# A line item's inline reference to its footnote, e.g.
# "Commitments and contingencies (Note 13)" on a balance-sheet row. Rare in
# the statement tables themselves (most footnote cross-referencing lives in
# surrounding narrative text, not the tables) — but exactly the structural
# link this graph exists to capture when present.
_INLINE_NOTE_REF_RE = re.compile(r"\(Note\s+(\d{1,2})\)", re.IGNORECASE)

# A numbered-heading match before this fraction of the document is treated
# as noise (front-matter/table-of-contents), not a real note heading — the
# statements + notes always fall well past the document's midpoint in a 10-K.
_MIN_BODY_FRACTION = 0.15

# Notes (especially "Segment Information") can run to tens of thousands of
# characters; cap what gets stored so a single footnote can't dominate a
# context window once Phase 5's footnote_tool starts serving these.
_MAX_NOTE_TEXT_CHARS = 4_000
_MAX_NOTE_BODY_SCAN_CHARS = 20_000  # bound the raw slice before truncation


def _extract_notes(text: str) -> dict[str, tuple[str, str]]:
    """
    {note_id: (note_title, note_text)} for every numbered note heading
    found. If a number's heading appears more than once (e.g. a stray
    duplicate match), the LAST one wins — headings are scanned in document
    order, so a later match always overwrites an earlier one, and the real
    section body always comes after any incidental earlier mention.
    """
    min_offset = int(len(text) * _MIN_BODY_FRACTION)
    matches = [m for m in _NOTE_HEADING_RE.finditer(text) if m.start() >= min_offset]
    notes: dict[str, tuple[str, str]] = {}
    for i, m in enumerate(matches):
        number, title = m.group(1), m.group(2).strip()
        body_start = m.end()
        next_start = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        body_end = min(body_start + _MAX_NOTE_BODY_SCAN_CHARS, next_start)
        body = text[body_start:body_end].strip()[:_MAX_NOTE_TEXT_CHARS]
        if body:
            notes[f"note_{number}"] = (title, body)
    return notes


def parse_footnote_graph(html: str) -> list[FootnoteLink]:
    """
    Parse a filing's footnote graph from its raw HTML:
      1. Extract every numbered note's (title, text) from the "Notes to ...
         Financial Statements" section.
      2. Walk every <table> for rows whose text contains a "(Note N)"
         inline reference, and link that row's own label to the matching note.

    Returns [] on any parse failure, or if nothing was found — this is
    best-effort enrichment layered on top of the XBRL numeric facts, never a
    hard requirement for ingestion to succeed.
    """
    try:
        soup = BeautifulSoup(html, "lxml")
        text = soup.get_text("\n")
        notes = _extract_notes(text)
        if not notes:
            return []

        links: list[FootnoteLink] = []
        seen: set[tuple[str, str]] = set()
        for table in soup.find_all("table"):
            for tr in table.find_all("tr"):
                row_text = tr.get_text(" ", strip=True)
                m = _INLINE_NOTE_REF_RE.search(row_text)
                if not m:
                    continue
                note_id = f"note_{m.group(1)}"
                if note_id not in notes:
                    continue
                statement_item = _INLINE_NOTE_REF_RE.sub("", row_text).strip(" -—")
                if not statement_item or (statement_item, note_id) in seen:
                    continue
                seen.add((statement_item, note_id))
                title, body = notes[note_id]
                links.append(FootnoteLink(
                    statement_item=statement_item, note_id=note_id,
                    note_title=title, note_text=body,
                ))
        return links
    except Exception as e:  # noqa: BLE001 — enrichment only, never fails ingestion
        logger.warning(f"[sec_html_parser] footnote graph parse failed: {e}")
        return []
